version: '3.8'

services:
  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
        MYSQL_DATABASE: ${MYSQL_DATABASE:-wichat_es4b}
        MYSQL_USER: ${MYSQL_USER:-wichat_es4b}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD:-wichat_es4b}
        MYSQL_PORT: ${MYSQL_PORT:-3306}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork
    restart: always

  wichat_es4b:
    build:
      context: .  # El directorio donde se encuentra tu código fuente (y Dockerfile)
      dockerfile: Dockerfile  # Asegúrate de que el nombre del Dockerfile sea correcto
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wichat_es4b}
      MYSQL_USER: ${MYSQL_USER:-wichat_es4b}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-wichat_es4b}
      MYSQL_PORT: ${MYSQL_PORT:-3306}
      KEYSTORE_PATH: ${KEYSTORE_PATH}
      KEYSTORE_PASSWORD: ${KEYSTORE_PASSWORD}
    ports:
      - "444:443"
    networks:
      - mynetwork
    depends_on:
      - db
    restart:
      always
    volumes:
      - ${KEYSTORE_PATH}:/certs/keystore.p12


  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - mynetwork
    depends_on:
      - wichat_es4b
    restart: always

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: 1
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    ports:
      - "3000:3000"
    networks:
      - mynetwork
    depends_on:
      - prometheus
    restart: always

volumes:
  db_data:
  prometheus_data:
  grafana_data:

networks:
  mynetwork:
    driver: bridge